package dbbwproject.serviceunit.dto;

import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.validation.constraints.NotBlank;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class NotificationDTO {
    @NotBlank
    @ApiModelProperty(notes = "System generated notification id. unique value", example = "N1")
    private String notificationId;

    @NotBlank
    @ApiModelProperty(notes = "Date which notification was generated by system. format yyyy-mm-dd", example = "2018-01-15")
    private String createdDate;

    @NotBlank
    @ApiModelProperty(notes = "Notification message", example = "sample notification text")
    private String message;

    @ApiModelProperty(notes = "Whether notification read by user", example = "false")
    private boolean isRead;
}
