package dbbwproject.serviceunit.dto;

import io.swagger.annotations.ApiModelProperty;
import lombok.*;

import javax.validation.constraints.NotBlank;
import javax.validation.constraints.Pattern;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class NotificationDTO {
    @NotBlank
    @ApiModelProperty(notes = "System generated notification id. unique value", example = "N1")
    private String notificationId;

    @NotBlank
    @Pattern(regexp = "^(\\d{4})\\D?(0[1-9]|1[0-2])\\D?([12]\\d|0[1-9]|3[01])(\\D?([01]\\d|2[0-3])\\D?([0-5]\\d)\\D?([0-5]\\d)?\\D?(\\d{3})?)?$"
            , message = "Created Date should be  in yyyy-MM-dd'T'HH:mm:ss.SSS format")
    @ApiModelProperty(notes = "Date which notification was generated by system. format yyyy-MM-dd'T'HH:mm:ss.SSS", example = "2019-12-21T13:10:26.641")
    private String createdDate;

    @NotBlank
    @ApiModelProperty(notes = "Notification message", example = "sample notification text")
    private String message;

    @ApiModelProperty(notes = "Whether notification read by user", example = "false")
    private boolean isRead;
}
